### ISSUE TITLE
gcc: error: unrecognized command-line option ‘-ftrivial-auto-var-init=zero’

### ISSUE THREAD

**Issue by kukuyok** [intel-gpu/intel-gpu-i915-backports#106]
```
Ubuntu 22.04.2
gcc 11.3.0
```

while upgrading kernel to last major ```5.19.17```

option is supported under ```gcc-12```

**Comment by ayazahma** [comment]
Thanks @kukuyok , we will try to reproduce and revert back

**Comment by eero-t** [comment]
@ayazahma any update on this?

**Comment by kukuyok** [comment]
@smuqthya sorry, I've already reinstalled OS on my laptop. It is Acer Swift 3 with i7-10510U.

As I can remember, I've been try to downgrade my kernel, as the major Ubuntu kernel version has been failed to boot.

**Comment by smuqthya** [comment]
This seems related to CLANG version. Please refer the change in kernel to warn. https://lore.kernel.org/all/20221010070333.780586109@linuxfoundation.org/ 

upgrade to latest.
