### ISSUE TITLE
docs: some issues need correction

### ISSUE THREAD

**Issue by dvrogozh** [intel-gpu/intel-gpu-i915-backports#13]
On primary readme:
```
[Intel® GPU firmware](https://github.com/intel-gpu/intel-gpu-i915-backports) - Firmware required by intel GPUs.
```
Link to FW is wrong and leads to i915-backports while should point to https://github.com/intel-gpu/intel-gpu-firmware.

On Ubuntu readme https://github.com/intel-gpu/intel-gpu-i915-backports/blob/ubuntu/main/README.md#prerequisite:
```
* dhelper

sudo apt install dkms make dhelper
```

There is no such package `dhelper` on Ubuntu. There is a package called `debhelper`. You also miss `build-essential` dependency.

**Comment by NitinGote** [comment]
Updated firmware link in https://github.com/intel-gpu/intel-gpu-i915-backports/pull/32 
Also updated packages in https://github.com/intel-gpu/intel-gpu-i915-backports/blob/ubuntu/main/README.md
