### ISSUE TITLE
Can i915 support accessing another PCIe's BAR from an iGPU?

### ISSUE THREAD

**Issue by yzim** [intel-gpu/intel-gpu-i915-backports#135]
I have been trying to let iGPU access the BAR of another PCIe device (e.g. an NVMe SSD). As noticing that pin_user_pages_fast() in i915_gem_object_userptr_submit_init() only supports normal memory, I modified the code in i915_gem_gtt_prepare_pages() to directly populate the sglist by the PCIe BAR's physical addresses (as done by other PCIe P2P code https://github.com/sbates130272/io_peer_mem/blob/master/io_peer_mem.c/). 

Although clCreateBuffer(..., CL_MEM_USE_HOST_PTR, mmapped_virt_addr_of_nvme_bar, ...) completes normally, the OpenCL kernel on iGPU cannot read the content of the PCIe BAR correctly, with all zeros returned.  

My hardware and software environments are:
H/W: Intel i9-9900KS, iGPU: UHD Graphics 630. (with IOMMU disabled)
S/W: Ubuntu 22.04.3 LTS, Linux 6.2.16.

Does any one know if it is limited by the hardware, that an iGPU cannot access a PCIe BAR, or by the software, that I missed some modifications in the i915 driver?
I failed to find a feedback channel to the original i915 repository, so I try to propose an issue here. Thanks!

**Comment by ayazahma** [comment]
i915 backport is being provided to support Discrete GPUs only and Integrated GPUs are not supported and tested. Please follow upstream support path for any iGPU related issue.

**Comment by yzim** [comment]
Could you please offer an upstream support url? I tried but didn't found. I also tried to contact to the Intel emails listed in the Linux git commits but have received no replies. Thank you!

**Comment by yzim** [comment]
Thank you! I will try it.
