### ISSUE TITLE
The gpu problem on N5105

### ISSUE THREAD

**Issue by wq2020wdm** [intel-gpu/intel-gpu-i915-backports#140]
I tried to install the latest rr boot with i915 on N5105. It successfully showed the render128 folder. But it failed when transcoding on emby, there was no hard decoding symbol. The gpu model shown was also wrong.
https://s2.loli.net/2023/11/15/X1RAO97yvKYUgVn.jpg
https://s2.loli.net/2023/11/15/8jHnV6LyaECAWOG.jpg
https://s2.loli.net/2023/11/15/F5SHx49w76Rt1QU.jpg

**Comment by Promix953** [comment]
你发错地方了
去RR那边反馈

**Comment by wq2020wdm** [comment]
发错了
