### ISSUE TITLE
Intel Datacenter Flex 140 + Kernel 6.5

### ISSUE THREAD

**Issue by flumm** [intel-gpu/intel-gpu-i915-backports#153]
Hi,

I am a software developer at Proxmox (Linux/KVM/Qemu based Virtualization Solution). I hope this is the correct repository, as https://github.com/intel/intel-data-center-gpu-driver-for-openshift links here regarding the Intel Datacenter GPU drivers.

I'd like to compile the drivers for an ubuntu based kernel 6.5 (since that's what we currently use) to use it for the Datacenter Flex 140 cards, but it does not compile (mostly uuid_le errors?).  Is newer kernel support on the horizon/planned? Anything i can do to help for that?

If there is a better place to discsuss/ask for this, please do tell.

Thanks

**Comment by smuqthya** [comment]
Hi @flumm , 

Current support for Ubuntu Desktop variant is 6.2. Please check versions file for latest support kernel information here https://github.com/intel-gpu/intel-gpu-i915-backports/blob/backport/main/versions#L5 . 

However, we are adding support for 6.5 as well, which should land in this repo soon.

**Comment by flumm** [comment]
That's great to hear, hopefully that lands soon :) I have one additional question, currently you/intel only support redhat/ubuntu for the datacenter gpus (flex140/170/etc.) Do you know who would we have to contact that Proxmox VE also could become a supported platform?

**Comment by ayazahma** [comment]
Hi , 6.5 is supported now, for other question I'll check but would you please let us know, which kernel is being used for Proxmox and how much it diverts from the mainline kernel

**Comment by flumm** [comment]
> Hi , 6.5 is supported now, for other question I'll check but would you please let us know, which kernel is being used for Proxmox and how much it diverts from the mainline kernel

thanks, that would be great!

our kernel is mostly a current ubuntu kernel (currently the 6.5 one) with zfsonlinux baked in and occasionally some minor patches (fixes+sometimes small backports, nothing too heavy), see https://git.proxmox.com/?p=pve-kernel.git;a=summary 

i don't think those would be anything that should impact the functionality of this driver

**Comment by smuqthya** [comment]
@flumm since latest driver with 6.5 support you could able to build. please check and confirm.

**Comment by scyto** [comment]
@flumm is this ready to try on promox VE test repo yet?

**Comment by flumm** [comment]
> @flumm since latest driver with 6.5 support you could able to build. please check and confirm.


> @flumm is this ready to try on promox VE test repo yet?

tested a bit with this and our current 6.5 kernel now and it worked ok, thanks. I'll be doing additional tests in the near future though. One has to be careful and use the correct firmware files though (though i guess they will land eventually in our own firmware package)

**Comment by scyto** [comment]
> > @flumm since latest driver with 6.5 support you could able to build. please check and confirm.
> 
> > @flumm is this ready to try on promox VE test repo yet?
> 
> tested a bit with this and our current 6.5 kernel now and it worked ok, thanks. I'll be doing additional tests in the near future though. One has to be careful and use the correct firmware files though (though i guess they will land eventually in our own firmware package)

definitely, for example I thought this would work on my 3 node NUC cluster with iGPU so i gave to a try

While the driver loads just fine in dmesg when a VM starts attached to the VF i get a spinlock/crash report in DMESG and qemu/KVM get very weird.... so definitely lots of testing needed before this goes downstream (i am assuming this is because I have iGPUs and this is not supported) and yes i think if this goes into mainline promox the promox folks suddenly become responsible for ensuring the rigth i915 firmware files are included... a lot ot think about...

strongtz i915-dkms repo works for me

**Comment by lleo19** [comment]
@flumm the dkms module version 1.24.1.11.240117.14 does build and work under kernel 6.5.13-3-pve but fails to build under the latest 6.5.3-5-pve
this is with an intel flex 140
I did not checked yet what changed in the latest update
`/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function â€˜intel_dp_mst_compute_link_configâ€™:
/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:87:35: error: too many arguments to function â€˜drm_dp_calc_pbn_modeâ€™
   87 |                 crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
      |                                   ^~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/backport-include/drm/drm_dp_mst_helper.h:27,
                 from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_display_types.h:38,
                 from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:38:
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
      |     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function â€˜intel_dp_dsc_mst_compute_link_configâ€™:
/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:165:35: error: too many arguments to function â€˜drm_dp_calc_pbn_modeâ€™
  165 |                 crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
      |                                   ^~~~~~~~~~~~~~~~~~~~
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
      |     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function â€˜intel_dp_mst_mode_valid_ctxâ€™:
/var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:913:13: error: too many arguments to function â€˜drm_dp_calc_pbn_modeâ€™
  913 |             drm_dp_calc_pbn_mode(mode->clock, min_bpp, false) > port->full_pbn) {
      |             ^~~~~~~~~~~~~~~~~~~~
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
      |     ^~~~~~~~~~~~~~~~~~~~
make[6]: *** [scripts/Makefile.build:251: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [scripts/Makefile.build:488: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915] Error 2
make[4]: *** [Makefile:2039: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build] Error 2
make[3]: *** [Makefile.build:13: modules] Error 2
make[2]: *** [Makefile.real:95: modules] Error 2
make[1]: *** [Makefile:75: modules] Error 2
make: *** [Makefile:59: default] Error 2
`

**Comment by eleven702** [comment]
> @flummdkms 模块版本 1.24.1.11.240117.14 可以在内核 6.5.13-3-pve 下构建和工作，但无法在最新的 6.5.3-5-pve 下构建， 这是使用 intel flex 140 我还没有检查发生了什么变化在最新的更新中
> 
> ```
>   CC [M]  /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/spi/intel_spi_drv.o
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_compute_link_config’:
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:87:35: error: too many arguments to function ‘drm_dp_calc_pbn_mode’
>    87 |                 crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
>       |                                   ^~~~~~~~~~~~~~~~~~~~
> In file included from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/backport-include/drm/drm_dp_mst_helper.h:27,
>                  from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_display_types.h:38,
>                  from /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:38:
> ./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
>   835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
>       |     ^~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_dsc_mst_compute_link_config’:
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:165:35: error: too many arguments to function ‘drm_dp_calc_pbn_mode’
>   165 |                 crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
>       |                                   ^~~~~~~~~~~~~~~~~~~~
> ./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
>   835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
>       |     ^~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_mode_valid_ctx’:
> /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:913:13: error: too many arguments to function ‘drm_dp_calc_pbn_mode’
>   913 |             drm_dp_calc_pbn_mode(mode->clock, min_bpp, false) > port->full_pbn) {
>       |             ^~~~~~~~~~~~~~~~~~~~
> ./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
>   835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
>       |     ^~~~~~~~~~~~~~~~~~~~
> make[6]: *** [scripts/Makefile.build:251: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915/display/intel_dp_mst.o] Error 1
> make[6]: *** Waiting for unfinished jobs....
> make[5]: *** [scripts/Makefile.build:488: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build/drivers/gpu/drm/i915] Error 2
> make[4]: *** [Makefile:2039: /var/lib/dkms/intel-i915-dkms/1.24.1.11.240117.14/build] Error 2
> make[3]: *** [Makefile.build:13: modules] Error 2
> make[2]: *** [Makefile.real:95: modules] Error 2
> make[1]: *** [Makefile:75: modules] Error 2
> make: *** [Makefile:59: default] Error 2
> ```

How to deal with it? I also have this error

**Comment by smuqthya** [comment]
@eleven702 / @lleo19 This issue is caused due to below change, which landed on kernel v6.6.14. This should not be seen in vanilla LTS 6.5. Unless this is backported to your custom kernel.  So we are not facing this issue. we will update the fix based on the  commit movements to LTS soon here.
 
commit 4e042f022255604c68ab5d5f73c8f437d24d651e
Author: Ville Syrj_l_ <ville.syrjala@linux.intel.com>
Date:   Tue Oct 24 04:08:57 2023 +0300

    drm/dp_mst: Fix fractional DSC bpp handling

    [ Upstream commit 7707dd6022593f3edd8e182e7935870cf326f874 ]
