### ISSUE TITLE
What is the latest method to dump vbios?

### ISSUE THREAD

**Issue by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [intel-gpu/intel-gpu-i915-backports#159]
Hi,
I want to dump the vbios of my intel computer and I have tried the method mentioned [here](https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/dump-video-bios.html)

However, the cat command resulting in following error:

```
cat: '/sys/bus/pci/devices/0000:00:02.0/rom': Input/output error
```

Here is another thread discussing the same problem: https://github.com/SpaceinvaderOne/Dump_GPU_vBIOS/issues/3

This is the live system I used:
https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-12.5.0-amd64-gnome.iso

Here are the pci devices that I have tried:
```
8086:9a49 Intel Corporation Tigher Lake-LP GT2 [Iris Xe Graphics] (rev 01)
8086:a780 Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770] (rev 04)
```

Failed work arounds: disable secure boot, disable kernel lockdown, blacklist i915 driver

**Comment by smuqthya** [comment]
i915 backport is being provided to support Discrete GPUs only and Integrated GPUs are not supported and tested. Please follow upstream support path for any iGPU related issue.
