### ISSUE TITLE
backport/main GPU support broken after latest commit on Kernel 5.14.0-427.40.1.el9_4.x86_64

### ISSUE THREAD

**Issue by upsj** [intel-gpu/intel-gpu-i915-backports#199]
After a kernel update, we rebuilt our GPU drivers, and while they can still attach successfully to the PCIe devices, they no longer get recognized by xpu-smi.

As a test, I built two versions of the drivers with Kernel 5.14.0-427.40.1.el9_4.x86_64 on Rocky 9.4:

* The driver based on https://github.com/intel-gpu/intel-gpu-i915-backports/commit/37b2e3814f0ac7550470419f49303dc7412e9839 works correctly for both A770 and PVC
* The driver based on the latest commit in the backport/main branch (https://github.com/intel-gpu/intel-gpu-i915-backports/commit/5d5c70c2908410029cd34d34b81eb4a16f6d24b6) fails with the following kind of error:

```
[   14.911185] i915 0000:9a:00.0: SPI access overridden by jumper
[   14.938235] i915 0000:ca:00.0: Using 112 cores (56-111,168-223) for kthreads
[   14.939894] i915 0000:ca:00.0: IAF available
[   14.940834] i915 0000:ca:00.0: Attaching to 262144MiB of system memory on node 1
[   14.940866] i915 0000:ca:00.0: Using Transparent Hugepages
[   14.940907] i915 0000:ca:00.0: GT0: Local memory { size: 0x0000000c00000000, available: 0x0000000bff000000 }
[   14.941043] i915 0000:ca:00.0: GT0: GuC firmware i915/pvc_guc_70.26.4.bin: fetch failed -ENOENT
[   14.941045] i915 0000:ca:00.0: GT0: GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   14.942672] i915 0000:ca:00.0: GT0: Can't run without GuC if GuC has previously been enabled
[   14.942794] i915 0000:ca:00.0: GT0: GuC initialization failed -ENOENT
[   14.942795] i915 0000:ca:00.0: GT0: Enabling uc failed (-5)
[   14.942796] i915 0000:ca:00.0: GT0: Failed to initialize GPU, declaring it wedged!
```

**Comment by smuqthya** [comment]
looks like firmware needs update.  Did you check if this firmware is part of device?

**Comment by upsj** [comment]
There is no such firmware file in the listed git repository - where can I find it and the necessary steps to upgrade the firmware?

**Comment by smuqthya** [comment]
https://github.com/intel-gpu/intel-gpu-i915-backports?tab=readme-ov-file#dependencies  Please check the Readme doc.
