### ISSUE TITLE
Custom compiled kernel support in debian based distros.

### ISSUE THREAD

**Issue by ddobreff** [intel-gpu/intel-gpu-i915-backports#33]
Hello,
Not actually generic issue, but for those who compile their own kernels in debian way there is no way of installing this package at all. It seeks for CONFIG_VERSION_SIGNATURE which in my case is empty. Are you planning on adding generic dkms support without distro limitation?
Thank you.

**Comment by smuqthya** [comment]
Hi @ddobreff, Thanks for bringing this to our attention. we will keep adding support for different kernel versions, yes in the future we will have support for the above.

**Comment by ddobreff** [comment]
Thank you for the quick answer @smuqthya.
My current kernel is 5.15.60 and as I see this version compiles fine upto 5.15.33, I'll be waiting for supported version.

**Comment by ddobreff** [comment]
Merged latest pull request and tried rebuilding, now its stuck here:
`DKMS make.log for intel-i915-dkms-0.6213.0.1.220914.2.5.17.15 for kernel 5.15.60-mmp (x86_64)
Fri Nov  4 13:00:38 UTC 2022
Generating local configuration database from kernel ... done.
cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer   -c -o conf.o conf.c
lex -ozconf.lex.c -L zconf.l
yacc -ozconf.tab.c -t -l zconf.y
cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer   -c -o zconf.tab.o zconf.tab.c
cc   conf.o zconf.tab.o   -o conf
#
# configuration written to .config
#
make[5]: 'conf' is up to date.
#
# configuration written to .config
#
Building backport-include/backport/autoconf.h ... done.
Building backport-include/backport/backport_path.h ... done.
  CC [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/main.o
  CC [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/backport-5.10.o
  CC [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/slub.o
  CC [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/slab.o
  LD [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/compat.o
WARNING: Symbol version dump "/var/lib/dkms/intel-platform-vsec-dkms/kernel-5.15.60-mmp-x86_64/build/Module.symvers" is missing.
         Modules may not have dependencies or modversions.
         You may get many unresolved symbol warnings.
  MODPOST /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/Module.symvers
  CC [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/compat.mod.o
  LD [M]  /var/lib/dkms/intel-i915-dkms/0.6213.0.1.220914.2.5.17.15/build/compat/compat.ko
`
Doesn't even start compiling i915 module.

**Comment by ddobreff** [comment]
Any update on this? Newest version still doesn't want to compile on anything but stock kernels.

**Comment by ddobreff** [comment]
Did some tricks and here's what it ended up with still prematurely exiting on finishing compat only:
```
echo "uts $UTS_RELEASE"
echo "base $BASE_KERN"
echo "ver $KERN_VER"
echo "osv $OSV_NAME"
echo "ver2 $KERN_VER"
echo "type $KERN_TYPE"
echo "x $EXTENDED_VERSION_X"
echo "y $EXTENDED_VERSION_Y"
---
generic kernel fully compiling output:
uts 5.15.0-52-generic
base 5.15
ver 5.15.0
osv UBUNTU
ver2 5.15.0
type generic
x 
y 
---
my kernel localversion -mmp
uts 5.15.75-mmp
base 5.15
ver 5.15.75
osv UBUNTU
ver2 5.15.75
type mmp
x 
y 
```
I would really appreciate some insights on why this may be failing on non stock kernels.

**Comment by ddobreff** [comment]
Advancement on the matter... it seems that it requires some kernel options enabled. Can you point me to kernel option requirements? I can't seem to find any in source.

**Comment by ddobreff** [comment]
Was missing MTD enabled. All fixed now! :)
