### ISSUE TITLE
476.14 dkms breaks VNC connection for VMs on 5.15.0-generic-50 Ubuntu kernel

### ISSUE THREAD

**Issue by dvrogozh** [intel-gpu/intel-gpu-i915-backports#57]
Seen on ATS-M. Did not try on Alchemist.

Consider https://github.com/intel/media-delivery/pull/135 which updates DKMS and virtualization setups for ATSM from 419 to 476.14 (dkms tags). Follow setups in this order:
1. Install Ubuntu 20.04
2. Use passthrough setup (or SRIOV, issue is reproducible on both): https://github.com/dvrogozh/media-delivery/blob/dkms/doc/virtualization.rst
3. Use Intel DKMS setup against 5.15.0-50 kernel: https://github.com/dvrogozh/media-delivery/blob/dkms/doc/intel-gpu-dkms.rst

You will find that VM VNC connection (which basically gives user prompt over VNC) will work with the VM till the moment when you will install Intel DKMS 476.14. As soon as you install it VNC screen will stuck somewhere in the middle of the kernel log. System will still be reachable with SSH, but VNC won't show console screen. This is regression in user experience comparing to 419 release and 5.14.0-oem-1045 kernel. Mind also, that on Ubuntu 22.04 there is no such issue if using 5.17.0-1019-oem kernel. I believe that there won't be such issue for 5.14.0-oem kernel on Ubuntu 20.04, but I did not verify that comprehensively.

Intel GPU stack in terms of media transcoding support still works fine despite of the issue (using SSH connection).

**Comment by eero-t** [comment]
@dvrogozh Is this (2022 issue) something that still happens with latest Ubuntu 5.15 kernels & DKMS versions?

**Comment by smuqthya** [comment]
@dvrogozh Assuming its not seen in latest as its too old. closing this issue. Please reopen if needed.
