### ISSUE TITLE
i915 driver no longer works with PMT driver

### ISSUE THREAD

**Issue by mregmi** [intel-gpu/intel-gpu-i915-backports#73]
We are using the latest commit of i915, PMT (vsec) and CSE driver. Our latest build failed to load the i915 driver. After debugging , we found out that in dmesg its complaining about the Vsec. 
`[508819.288281] i915: Unknown symbol intel_vsec_register (err 0)`
Even after loading the vsec driver, the issue continues. So it looks like i915 driver is also not compatible for RHEL. We are using 'redhat/main' branch.

**Comment by mregmi** [comment]
We are not using tags and cloning the latest. We are on RHEL 8.6 and kernel version is `4.18.0-372.26.1.el8_6.x86_64`

**Comment by uMartinXu** [comment]
@mregmi we should use the official release tag like i915 driver: [RHEL86_22WW45.5_476.14_6213_220914.1](https://github.com/intel-gpu/intel-gpu-i915-backports/releases/tag/RHEL86_22WW45.5_476.14_6213_220914.1)
PMT driver: [22WW45.5_476.14_RHEL86](https://github.com/intel-gpu/intel-gpu-pmt-backports/releases/tag/22WW45.5_476.14_RHEL86)
And PMT and i915 driver combination rule is use the same agama version which is 467.14 in the above example.
So suggest closing the issue, if you still find the issue with the above combination, please file an other issue with detailed tag and version information. Thanks!

**Comment by mregmi** [comment]
closing this as we are falling back to the older tag that works.
