### ISSUE TITLE
i7-13700h  Linux gpu Driver Support？

### ISSUE THREAD

**Issue by ggddver** [intel-gpu/intel-gpu-i915-backports#83]
my laptop is  Lenovo ThinkBook 14+ 2023   i7-13700h, when I install Ubuntu22.04 or LinuxMint 21.1 and update the kernel version to the latest version (5.19 and 6.1 oem version),   the gpu is working but  render very very slow....the mouse move so slow。。I also tried intel  kernel 5.17-oem。。but unsolved。。how can I do？
 (the pci code  is 0xa7a0)

**Comment by smuqthya** [comment]
KMD backport is intended for Discrete platforms only and we do not test igpu with dkms and neither claim to support. Closing this issue.,
